Add test-status

diff --git a/.github/workflows/matrix.yml b/.github/workflows/matrix.yml
--- a/.github/workflows/matrix.yml
+++ b/.github/workflows/matrix.yml
@@ -40,3 +40,29 @@ jobs:
       - name: Echo
         run: |
           echo "Run: ${{ matrix.run }}"
+
+  test-status:
+    needs: test
+    if: ${{ always() }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: Success
+        if: ${{ needs.test.result == 'success' }}
+        run: |
+          echo "Test was a success"
+          exit 0
+      - name: Skipped
+        if: ${{ needs.test.result == 'skipped' }}
+        run: |
+          echo "Test was skipped"
+          exit 0
+      - name: Cancelled
+        if: ${{ needs.test.result == 'cancelled' }}
+        run: |
+          echo "Test was cancelled"
+          exit 1
+      - name: Failure
+        if: ${{ needs.test.result == 'failure' }}
+        run: |
+          echo "Test was a failure"
+          exit 1
